// Generated by CoffeeScript 1.8.0
(function() {
  var $, CheckFileExists;

  if (typeof jQuery === "undefined" || jQuery === null) {
    $ = require("jquery");
  }

  if ($ == null) {
    $ = jQuery;
  }

  CheckFileExists = (function() {
    CheckFileExists.DEFAULTS = {
      headers: {}
    };

    function CheckFileExists(files, options) {
      var file, _i, _len;
      this.files = files;
      this.options = $.extend(CheckFileExists.DEFAULTS, options);
      this.filenames = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        this.filenames.push(file.name);
      }
      this._jqXHR = null;
      this._deferred = $.Deferred();
      this._deferred.promise(this);
    }

    CheckFileExists.prototype._checkFiles = function() {
      var headers, options;
      headers = $.extend({}, this.options.headers);
      options = {
        type: 'POST',
        url: "" + this.options.endpoint + "check",
        cache: false,
        contentType: "application/json; charset=UTF-8",
        headers: headers,
        processData: false,
        data: JSON.stringify({
          "filenames": this.filenames
        })
      };
      return this._jqXHR = $.ajax(options).fail((function(_this) {
        return function(jqXHR, textStatus, errorThrown) {
          return _this._emitFail(new Error("" + textStatus + ": " + errorThrown));
        };
      })(this)).done((function(_this) {
        return function(data, textStatus, jqXHR) {
          var file, foundFiles, foundFilesString, _i, _len, _ref;
          if (data.results == null) {
            _this._emitFail(new Error("Bad Response"));
            return;
          }
          foundFiles = [];
          foundFilesString = '';
          _ref = data.results;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            file = _ref[_i];
            if (file.status === 'found') {
              foundFiles.push(file);
              foundFilesString += file.name + ', ';
            }
          }
          foundFilesString = foundFilesString.substr(0, foundFilesString.length - 2);
          if (foundFiles.length > 0) {
            return _this._emitFail({
              foundFiles: foundFiles,
              results: data.results,
              foundFilesString: foundFilesString,
              status: 'found'
            });
          } else {
            return _this._emitDone();
          }
        };
      })(this));
    };

    CheckFileExists.prototype.stop = function() {
      if (this._jqXHR != null) {
        return this._jqXHR.abort();
      }
    };

    CheckFileExists.prototype._emitDone = function() {
      return this._deferred.resolveWith(this, [this.files]);
    };

    CheckFileExists.prototype._emitFail = function(err, status) {
      return this._deferred.rejectWith(this, [err, status]);
    };

    return CheckFileExists;

  })();

  module.exports = CheckFileExists;

}).call(this);

//# sourceMappingURL=CheckFileExists.js.map
