// Generated by CoffeeScript 1.8.0
(function() {
  var $, CheckFileExists, FileChecksum, PolyResumableUpload, Q, ResumableUpload;

  if (typeof jQuery === "undefined" || jQuery === null) {
    $ = require("jquery");
  }

  if ($ == null) {
    $ = jQuery;
  }

  if (global.Q == null) {
    Q = require("q");
  }

  if (global.Q != null) {
    Q = global.Q;
  }

  ResumableUpload = require("./ResumableUpload");

  PolyResumableUpload = require("./PolyResumableUpload");

  CheckFileExists = require("./CheckFileExists");

  FileChecksum = require("./FileChecksum");

  global.gr = global.gr || {};

  global.gr.polyptychon = global.gr.polyptychon || {};

  global.gr.polyptychon.tus = {
    upload: function(file, options) {
      var deferred, upload;
      deferred = Q.defer();
      upload = new PolyResumableUpload(file, options);
      file.action = upload;
      upload.fail(function(error, status) {
        file.action = null;
        return deferred.reject(new Error({
          error: error,
          status: status
        }));
      });
      upload.progress(function(e, bytesUploaded, bytesTotal) {
        var percentage;
        percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
        return deferred.notify(percentage);
      });
      upload.done(function(url, file, md5) {
        file.action = null;
        if (file.md5) {
          if (file.md5 === md5) {
            return deferred.resolve({
              url: url,
              file: file,
              md5: md5
            });
          } else {
            return deferred.reject(new Error("Checksum does not match. " + file.md5 + " != " + md5));
          }
        } else {
          file.md5 = md5;
          return deferred.resolve({
            url: url,
            file: file,
            md5: md5
          });
        }
      });
      if (file) {
        upload._start();
      }
      return deferred.promise;
    },
    check: function(file, options) {
      var check, deferred;
      deferred = Q.defer();
      check = new CheckFileExists(file, options);
      if (file) {
        check._checkFileExists();
      }
      check.fail(function(error, status) {
        return deferred.resolve(file);
      }).done(function(url, file) {
        return deferred.reject({
          message: "File already exist",
          file: file
        });
      });
      return deferred.promise;
    },
    checksum: function(file, options) {
      var checksum, deferred;
      deferred = Q.defer();
      checksum = new FileChecksum(file, options);
      file.action = checksum;
      checksum.fail(function(error) {
        file.action = null;
        return deferred.reject(new Error(error));
      });
      checksum.progress(function(e, bytesUploaded, bytesTotal) {
        var percentage;
        percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
        return deferred.notify(percentage);
      });
      checksum.done(function(file, md5) {
        file.action = null;
        file.md5 = md5;
        return deferred.resolve({
          file: file,
          md5: md5
        });
      });
      if (file) {
        checksum._computeChecksum(0);
      }
      return deferred.promise;
    },
    stop: function(file) {
      if (file.action) {
        return file.action.stop();
      }
    },
    checkAll: function(files, options) {
      var file, promises, _i, _len;
      promises = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        promises.push(this.check(file, options));
      }
      return Q.all(promises);
    },
    checksumAll: function(files, options) {
      var file, promises, _i, _len;
      promises = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        promises.push(this.checksum(file, options));
      }
      return Q.all(promises);
    },
    uploadAll: function(files, options) {
      var file, promises, _i, _len;
      promises = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        promises.push(this.upload(file, options));
      }
      return Q.all(promises);
    },
    stopAll: function(files) {
      var file, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        _results.push(this.stop(file));
      }
      return _results;
    },
    UploadSupport: ResumableUpload.SUPPORT
  };

  module.exports = global.gr.polyptychon.tus;

}).call(this);

//# sourceMappingURL=Tus.js.map
