// Generated by CoffeeScript 1.7.1
(function() {
  var $, CheckFileExists, PolyResumableUpload;

  $ = require("jquery");

  PolyResumableUpload = require("./PolyResumableUpload");

  CheckFileExists = require("./CheckFileExists");

  module.exports = {
    upload: function(file, options) {
      var upload;
      upload = new PolyResumableUpload(file, options);
      if (file) {
        upload._start();
      }
      return upload;
    },
    check: function(file, options) {
      var check;
      check = new CheckFileExists(file, options);
      if (file) {
        check._checkFileExists();
      }
      return check;
    }
  };

}).call(this);

//# sourceMappingURL=Tus.map
