// Generated by CoffeeScript 1.8.0
(function() {
  global.$ = global.jQuery = require("jquery");

  global.Q = require("q");

  global.SparkMD5 = require("spark-md5");

}).call(this);

//# sourceMappingURL=TusVendors.js.map
